package crimebuster.model;

import java.util.Date;

public class CrimeReports {

  protected long ReportId;
  protected Users user;
  protected Date occurredTimeStamp;
  protected Date reportedTimeStamp;
  protected CrimeCategory initialCallType;
  protected CrimeCategory finalCallType;
  protected BeatSector beat;
  protected Neighborhood neighborhood;
  protected Zipcode zipcode;

  /**
   * This constructor can be used for reading CrimeReports from MySQL, where we have all fields,
   * including the ReportId.
   */
  public CrimeReports(long reportId, Users user, Date occurredTimeStamp,
      Date reportedTimeStamp, CrimeCategory initialCallType, CrimeCategory finalCallType,
      BeatSector beat, Neighborhood neighborhood, Zipcode zipcode) {
    this.ReportId = reportId;
    this.user = user;
    this.occurredTimeStamp = occurredTimeStamp;
    this.reportedTimeStamp = reportedTimeStamp;
    this.initialCallType = initialCallType;
    this.finalCallType = finalCallType;
    this.beat = beat;
    this.neighborhood = neighborhood;
    this.zipcode = zipcode;
  }

  /**
   * This constructor can be used for reading CrimeReports from MySQL, where we only have the
   * ReportId, such as a foreign key reference to ReportId. Given ReportId, we can fetch the full
   * CrimeReports record.
   */
  public CrimeReports(long reportId) {
    this.ReportId = reportId;
  }

  /**
   * This constructor can be used for creating new CrimeReports, where the ReportId may not be
   * assigned yet since it is auto-generated by MySQL.
   */
  public CrimeReports(Users user, Date occurredTimeStamp, Date reportedTimeStamp,
      CrimeCategory initialCallType, CrimeCategory finalCallType, BeatSector beat,
      Neighborhood neighborhood, Zipcode zipcode) {
    this.user = user;
    this.occurredTimeStamp = occurredTimeStamp;
    this.reportedTimeStamp = reportedTimeStamp;
    this.initialCallType = initialCallType;
    this.finalCallType = finalCallType;
    this.beat = beat;
    this.neighborhood = neighborhood;
    this.zipcode = zipcode;
  }

  public long getReportId() {
    return ReportId;
  }

  public void setReportId(long reportId) {
    ReportId = reportId;
  }

  public Users getUser() {
    return user;
  }

  public void setUser(Users user) {
    this.user = user;
  }

  public Date getOccurredTimeStamp() {
    return occurredTimeStamp;
  }

  public void setOccurredTimeStamp(Date occurredTimeStamp) {
    this.occurredTimeStamp = occurredTimeStamp;
  }

  public Date getReportedTimeStamp() {
    return reportedTimeStamp;
  }

  public void setReportedTimeStamp(Date reportedTimeStamp) {
    this.reportedTimeStamp = reportedTimeStamp;
  }

  public CrimeCategory getInitialCallType() {
    return initialCallType;
  }

  public void setInitialCallType(CrimeCategory initialCallType) {
    this.initialCallType = initialCallType;
  }

  public CrimeCategory getFinalCallType() {
    return finalCallType;
  }

  public void setFinalCallType(CrimeCategory finalCallType) {
    this.finalCallType = finalCallType;
  }

  public BeatSector getBeat() {
    return beat;
  }

  public void setBeat(BeatSector beat) {
    this.beat = beat;
  }

  public Neighborhood getNeighborhood() {
    return neighborhood;
  }

  public void setNeighborhood(Neighborhood neighborhood) {
    this.neighborhood = neighborhood;
  }

  public Zipcode getZipcode() {
    return zipcode;
  }

  public void setZipcode(Zipcode zipcode) {
    this.zipcode = zipcode;
  }
}
